import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@melony/ui/globals.css";

import { MelonyApp } from "@melony/views";
import { melony } from "@/melony";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<MelonyApp config={melony} />
			</body>
		</html>
	);
}
